[project]
name = "chat-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sivakumar232", email = "sivakumarr3105@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "dotenv>=0.9.9",
    "google-genai>=2.22.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-google-genai>=4.4.0",
    "langchain-qdrant>=1.1.0",
    "markdownify>=1.2.3",
    "pypdf>=6.16.2",
    "qdrant-client>=1.19.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "pysbd>=0.3.4",
    "tiktoken>=0.14.0",
    "groq>=1.7.0",
    "rank-bm25>=0.2.2",
    "langgraph>=1.2.11",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
    "langsmith>=0.12.1",
    "nemoguardrails>=0.24.1",
    "openai>=3.17.0",
]

[project.scripts]
chat-bot = "chat_bot:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
index-strategy = "unsafe-best-match"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"


[tool.pyright]
include = ["."]
extraPaths = ["."]

[tool.pyrefly]
project-includes = ["."]
search-path = ["."]

